export const organisationals = [
  'apprentice',
  'junior',
  'specialist',
  'senior',
  'manager',
  'executive',
  'company owner',
  'intern',
  'in finance',
  'in business',
  'volunteer',
  'creative',
  'in the energy sector',
  'in egnineering',
  'environment',
  'in healthcare',
  'store worker',
  'armed forces',
  'farming',
  'part of an organisation with a clan culture',
  'part of an organisation with Adhocracy culture',
  'part of an organisation with market culture',
  'part of an organisation with hierarchical culture',
  'part of an organisation with risk-averse culture',
  'part of an organisation with goal-oriented culture',
  'part of an organisation with expert culture',
  'part of an organisation with discipline-centered culture',
  'part of an organisation with local culture',
  'part of an organisation with open culture',
  'retired',
  'self-employed',
  'employed',
  'unemployed',
  'part-time',
  'full-time',
  'contractor',
  'job-seeker',
  'finance professional',
  'business professional',
  'volunteer',
  'creative professional',
  'energy professional',
  'engineer',
  'environmental activist',
  'healthcare professional',
  'in store worker'
];
