// Personal Dimensions
const personalDimensions1 =
  'without formal education,with trade certifications,with Masters Degree,Home schooled,with Graduate degree,low income,medium income,high income,with inherited wealth,into 3D printing,into Acting,into Building,into Cabaret,into Calligraphy,into Computer programming,into Cooking,into Dance,into Do it yourself,into Electronics,into Fashion design,into Fishfarming,into Filmmaking,into Furniture building,into Tabletop gaming,into Gymnastics,into Hacking,into Hydroponics,into Ice skating,into Knitting,into Knot tying,into Kombucha brewing,into Lace making,into Lapidary,into Leather crafting,into Lego building,into Livestreaming,into Lying,into Machining,into Mechanics,into Macrame,into Magic,into Meditation,into Music,into Photography,into Pilates,into Pressed flower craft,into Quilting,into Pottery,into Powerlifting,into SCUBA Diving,into Spreadsheets,into Vegetable farming,into Vehicle restoration,into Videography,into Walking,into Water sports,into Astronomy,into Biology,into Chemistry,into Physics,into Backgammon,';
const personalDimensions2 =
  'into Bowling,into Fencing,into Kabaddi,into Knowledge/word games,into Laser tag,into Longboarding,into Magic,into Mahjong,into VR Gaming,into Weightlifting,into Australian rules football,into Cricket,into Croquet,into Cycling,into Longboarding,into Long-distance running,into Quidditch,into Race walking,into Skateboarding,into Skiing,into Sled dog racing,into Swimming,into Table tennis,into Tennis,into Triathlon,into Ultimate frisbee,into Volleyball,into Water polo,into Meditation,into Microscopy,into Reading,cohabiting,single,married,widowed,divorced,polygamous,separated,parent,step-parent,guardian,foster parent,custodian,living in a wealthy area,living in a mixed area,living in a deprived area,living in a dangerous area,homeowner,landlord,renter,homeless,in supported housing,';
const personalDimensions3 =
  'in social housing,on holiday,living with parents,nomadic,flat-sharing,landowner,dressed in Streetwear Style,dressed in Ethnic fashion style,dressed in Formal Office Wear,dressed in Business Casual,dressed in Evening Black Tie,dressed in Sports Wear,dressed in Girly Style,dressed in fashion style,dressed in Rocker Chic Style,dressed in Skateboarders,dressed in Goth Fashion,dressed in Maternity Style,dressed in Gothic style,dressed in Hip Hop Style,dressed in Kawaii fashion,dressed in Casual Chic Style,dressed in Geeky chic Style,dressed in Military style,dressed in Retro Fashion,dressed like a Tomboy,dressed in Vacation (Resort) style,dressed in Artsy Fashion style,dressed in Grunge style,dressed in Punk,dressed in Boho/Bohemian chic,dressed in Biker fashion,';
const personalDimensions4 =
  "dressed in Psychedelic Fashion style,dressed in Cosplay Fashion,dressed in Haute Couture,dressed modestly,christian,muslim,hindu,buddhist,sikh,taoist,jew,confucian,bahá'í,shintoist,jain,rastafarian,zoroastrian,spanish-speaking,english-speaking,Hindi-speaking,Bengali-speaking,Portuguese-speaking,Russian-speaking,Japanese-speaking,Punjabi-speaking,Marathi-speaking,Telugu-speaking,Chinese-speaking,Turkish-speaking,Korean-speaking,French-speaking,German-speaking,Vietnamese-speaking,Tamil-speaking,Urdu-speaking,Javanese-speaking,Italian-speaking,Egyptian Arabic-speaking,Gujarati-speaking,Iranian Persian-speaking,Bhojpuri-speaking,Polish - speaking,Indonesian -speaking,Ukrainian-speaking,ambitious,assertive,chatty,cheerful,charming,funny,kind,mature,reliable,easy-going,loyal,outgoing,open-minded,sensitive,sensible,selfless,";
const personalDimensions5 =
  'thoughtful,trustworthy,smart,wise,arrogant,closed-minded,disorganised,immature,selfish,vain,advanced,forgetful,insecure,insincere,moody,stubborn,spoilt,from Bangor,from Bar,from Benecassim,from Brixton,from Birmingham,from Essen,from Hamburg,from Cannes,from Gouda,from Heraklion,from Podgorica,from Malibu,from Madrid,from Osaka,from Oslo,from Cancun,Australian,Chinese,Dutch,Irish,Namibian,Latvian,Iranian,Somali,Bangladeshi,Vietnamese,with curly hair,with no hair,blonde,brunet,red-head,with straight hair,with wavy hair,with a ponytail,with a fringe,bearded,without facial hair,with a goatee,with a moustache,with sideburns,with a belly/ paunch,slim – to be the correct weight,skinny/thin – to be underweight,overweight,well-built,tall,short,medium height,Beautiful,Pretty,Cute,Handsome,Good-looking,Unattractive,With freckles,With rosy cheeks';

export const concatenatedDimensions =
  personalDimensions1 +
  personalDimensions2 +
  personalDimensions3 +
  personalDimensions4 +
  personalDimensions5;

export const personals = concatenatedDimensions.split(',');
